// apps/provider-inject/src/components/Counter.vue
<template>
  <div>
    <CounterView />
    <IncrementButton />
    <DecrementButton />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

import CounterView from './CounterView.vue';
import DecrementButton from './DecrementButton.vue';
import IncrementButton from './IncrementButton.vue';

export default defineComponent({
  name: 'Counter',
  components: { DecrementButton, IncrementButton, CounterView },
});
</script>

<style scoped></style>

// apps/react-context/src/app/components/Counter.tsx
import { memo, VFC } from 'react';

import { CounterView } from './CounterView';
import { DecrementButton } from './DecrementButton';
import { IncrementButton } from './IncrementButton';

export const Counter: VFC = memo(() => {
  console.log('render:Counter');
  return (
    <div>
      <CounterView />
      <IncrementButton />
      <DecrementButton />
    </div>
  );
});
