// apps/react-context/src/app/Counter.tsx
import { VFC } from 'react';
import { IncrementButton } from './IncrementButton';
import { CounterView } from './CounterView';
import { DecrementButton } from './DecrementButton';

export const Counter: VFC = () => {
  return (
    <div>
      <CounterView />
      <IncrementButton />
      <DecrementButton />
    </div>
  );
};

// apps/provider-inject/src/components/Counter.vue
<template>
  <div>
    <CounterView />
    <IncrementButton />
    <DecrementButton />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

import CounterView from './CounterView.vue';
import DecrementButton from './DecrementButton.vue';
import IncrementButton from './IncrementButton.vue';

export default defineComponent({
  name: 'Counter',
  components: { DecrementButton, IncrementButton, CounterView },
});
</script>

<style scoped></style>
