// apps/provider-inject/src/App.vue
<template>
  <div>
    <Header />
    <Main />
    <Footer />
  </div>
</template>

<script lang="ts">
import { defineComponent, provide } from 'vue';

import Footer from './components/Footer.vue';
import Header from './components/Header.vue';
import Main from './components/Main.vue';
import { counterInjectionToken, useCounter } from './composables/use-counter';

export default defineComponent({
  name: 'App',
  components: {
    Footer,
    Main,
    Header,
  },
  setup() {
    provide(counterInjectionToken, useCounter());

    return {};
  },
});
</script>

// apps/react-context/src/app/app.tsx
import { Header } from './components/Header';
import { Main } from './components/Main';
import { Footer } from './components/Footer';
import { createContext } from 'react';
import { useCounter } from './hooks/useCounter';

export type StoreType = ReturnType<typeof useCounter>;

export const CounterContext = createContext<StoreType | undefined>(undefined);

export const App = () => {
  const value = useCounter();

  return (
    <CounterContext.Provider value={value}>
      <Header />
      <Main />
      <Footer />
    </CounterContext.Provider>
  );
};

export default App;
